import { z } from 'zod'

/**
 * The wire contract for POST /api/checkout.
 *
 * Extracted from the route handler so it can be unit tested. The single most
 * important property of this whole system is provable here without a database:
 *
 *   the request shape has no field through which a client can influence price.
 *
 * zod strips unknown keys by default, so a body carrying `total`, `amount` or
 * `unitPrice` does not merely get ignored by the pricing engine, it never
 * reaches it. tests/checkout-contract.test.ts asserts exactly that.
 */
export const checkoutBodySchema = z.object({
  offerCode: z.string().min(1, 'অফার নির্বাচন করুন').max(64),
  couponCode: z.string().max(64).optional().nullable(),
  name: z.string().min(1, 'নাম দিন').max(120, 'নামটি অত্যধিক দীর্ঘ'),
  email: z.string().email('সঠিক ইমেইল দিন').max(254, 'ইমেইলটি অত্যধিক দীর্ঘ'),
  phone: z.string().max(32, 'নম্বরটি অত্যধিক দীর্ঘ').optional().default(''),
  // Generated by our own client, never typed by a person, so the message here
  // exists only so a malformed programmatic call does not surface raw English
  // validator output to a customer.
  idempotencyKey: z
    .string()
    .min(8, 'অনুরোধটি সঠিক নয়')
    .max(128, 'অনুরোধটি সঠিক নয়'),
  attribution: z.record(z.string().max(256)).optional().default({}),
})

export type CheckoutBody = z.infer<typeof checkoutBodySchema>

/** Attribution is attacker-controlled and is displayed in the admin. */
export const MAX_ATTRIBUTION_KEYS = 20

export function limitAttribution(input: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(input).slice(0, MAX_ATTRIBUTION_KEYS))
}
